FROM node:18-alpine

WORKDIR /app

# 设置时区
RUN apk add --no-cache tzdata
ENV TZ=Asia/Shanghai

# 设置 npm 镜像源（中国镜像）
RUN npm config set registry https://registry.npmmirror.com

# 安装基础依赖
RUN npm install -g pnpm

# 复制 package.json 并安装依赖
COPY package*.json ./
RUN pnpm install

# 复制源代码
COPY . .

# 暴露端口
EXPOSE 3000

CMD ["npm", "run", "start"]
